# Generated by Django 4.2.6 on 2023-10-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6-g6RtuMHoRdlcBwoNSO-TENKF_GBxzZntIQ_BJD2&s', max_length=500),
        ),
    ]
